name: Deploy to Kubernetes

on:
  workflow_dispatch:
  repository_dispatch:
    types: [ deployment ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Check out the code (only needed if deploying YAML files from repo)
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up kubectl
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      # Create .kube directory
      - name: Create .kube directory
        run: mkdir -p ~/.kube

      # Set up KubeConfig
      - name: Set up KubeConfig
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: echo "$KUBECONFIG" > ~/.kube/config

      # Deploy to Kubernetes
      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f k8s/namespace.yaml
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
